# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: example.com
  secret_key_base: 99f46bbeeb2eaa0c479f5f4c734b414c2d5c4a47509c9f5511e6a7b68811f35037f7a2486f83e89f0afe02ca3bff690cb69df4ecf0659b3db72cb8ed18e6b259
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  aws_s3_bucket: <%= ENV["S3_BUCKET_NAME"] %>
  aws_s3_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_s3_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


test:
  domain_name: example.com 
  secret_key_base: 9cd505edf8557a575aa90050fc75715bce0925f4db5a020bb6b8cb6c14ca192dcadc5e7c50b8061f47f553f592806a2745217d088f0640692240f164e4c02c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  aws_s3_bucket: <%= ENV["S3_BUCKET_NAME"] %>
  aws_s3_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_s3_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


